# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: pim
