### Get all attributes
GET http://localhost:4000/api/attributes

### Get one attribute
GET http://localhost:4000/api/attributes/1

### Post one attributes
POST http://localhost:4000/api/attributes
content-type: application/json

{
  "name": "tjhyergst",
  "type": "Single Select",
  "description": "this is description",
  "default_value": "test text",
  "max": 100,
  "min": 5,
  "required": true,
  "unit": "Hertz",
  "locals": [
    {
      "id": 1,
      "local" : "I am an english label"
    },
    {
      "id": 2,
      "local" : "I am another label"
    }
  ],
  "groups": [3,4],
  "choices": ["choice 1", "foo bar "]
}

### Update one attributes
PATCH http://localhost:4000/api/attributes/4
content-type: application/json

{
  "name": "test edits yyhere",
  "type": "Multiple Select",
  "description": "this is description",
  "default_value": "test text",
  "min": 2,
  "max": 100,
  "required": true,
  "unit": "Hertz",
  "locals": [
    {
      "id": 1,
      "local" : "This is english label"
    },
    {
      "id": 2,
      "local" : "I am an english label"
    }
  ],
  "choices": ["choice 1", "foo bar "]
}


### Delete one attribute
DELETE http://localhost:4000/api/attributes/3
